#!/usr/bin/env python
# encoding: utf-8

def build(bld):

    source = bld.path.ant_glob('*.cpp')
    source += bld.path.ant_glob('../../ecos/src/*.c')
    source += bld.path.ant_glob('../../ecos/external/amd/src/*.c')
    source += bld.path.ant_glob('../../ecos/external/ldl/src/*.c')

    print(source)

    bld.ap_program(
        use='ap',
        program_groups=['examples'],
        source=source,
    )

